POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@13"
}


###
GET http://localhost:3000/states/
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjE3ODcxMTM4fQ.5JYib4_kSzmFe-x5QKsX26pOL-Za63FNeWjk85EubMo

###
GET http://localhost:3000/states/4/
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjE3ODcxMTM4fQ.5JYib4_kSzmFe-x5QKsX26pOL-Za63FNeWjk85EubMo

###
POST http://localhost:3000/districts/
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjE3ODcxMTM4fQ.5JYib4_kSzmFe-x5QKsX26pOL-Za63FNeWjk85EubMo
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###
GET http://localhost:3000/districts/1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjE3ODcxMTM4fQ.5JYib4_kSzmFe-x5QKsX26pOL-Za63FNeWjk85EubMo

###
PUT http://localhost:3000/districts/765
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjE3ODcxMTM4fQ.5JYib4_kSzmFe-x5QKsX26pOL-Za63FNeWjk85EubMo
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

###
GET http://localhost:3000/states/4/stats
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjE3ODcxMTM4fQ.5JYib4_kSzmFe-x5QKsX26pOL-Za63FNeWjk85EubMo
